import random
file= open("t_InsertOutput.txt", "w")

# Generate 100 random boolean values
# random_values = [random.choice(["",""]) for _ in range(100)]
# print(random_values)

# items= ['enchanted amulet', 'crystallized essence', "dreamweaver's quill", 'gilded compass', 'whispering totem', 'lunar crest', 'thunderstruck relic', 'enigmatic scroll', 'radiant prism', 'galeforce whistle', 'arcane codex', "stormbringer's sigil", 'crystallized tears', 'enigmatic crest', 'sacred sigil', 'soothing breeze amulet', 'dreamcatcher amulet', "stargazer's lens", 'vortex core', 'celestial ocarina', 'stormwhisper feather', 'astral serpent scale', 'crimson phoenix plume', 'sylphic whisper', 'echoing chime', 'obsidian rune stone', "dreamer's journal", 'lunar blossom', 'enigmatic figurine']
# values= [True,True,False,False,True,True,True,False,False,True,True,True,False,True,False,True,True,False,True,False,False,False,False,True,True,False,False,False,True,False,False,True,True,True,True,False,False,False,True,False,True,True,False,True,False,False,False,True,False,False,False,True,False,False,False,True,True,True,False,False,True,False,False,True,False,True,False,True,True,True,False,False,False,False,False,False,False,True,True,True,False,True,True,True,True,False,False,False,False,True,True,True,False,True,True,True,False,True,True,False]
# final= []
# for i in values:
#     if i:
#         recipe= []
#         for j in range(random.randint(2,4)):
#             recipe.append(random.choice(items))
#         final.append(recipe)
    
#     else:
#         final.append('null')

# print(final)


############################ GENERATE PLAYERS ##########################################################################
weapons= ["nichirin blade","wooden bow","silver sword","samurai's katana","playful nunchucks","blade of the heavens","bow of the ancients","staff of chaos","plasma rifle","sniper rifle","frostblade","iron warhammer","shadow dagger","fire whip","thunder staff","poisoned crossbow","mystic scepter","demon's trident","lunar shuriken","vortex gauntlets","acidic whip","ruby scimitar","starlight wand","void dagger","lava axe","ethereal rapier","phoenix bow","mindflayer's staff","plasma blade","arcane bow","viper's fang","graviton cannon","serpent's staff","ice shard thrower","celestial sword","chrono bow","dark matter scythe","solar blaster","nebula wand","nova rifle","shadowstrike dagger","thorned whip","ember axe","lightning spear","blizzard staff","venomous crossbow","astral sword","oceanic trident","crimson shuriken","skyward bow","phantom blade","obsidian scythe","starfall wand","void cannon","molten whip","ethereal rapier","inferno bow","mindbender's staff","energy blade","spirit bow","frostbite fang","quantum blaster","serpent's gaze staff","glacial spear thrower","heavenly saber","time-bender bow","voidcleaver scythe","stellar blaster","galactic wand","darkstar rifle","phantasmal dagger","stormcaller whip","cinderblade","volt lance","glacier staff","toxic crossbow","luminous saber","abyssal trident","azure shuriken","celestial bow","shadowmeld blade","voidreaper scythe","cosmic wand","chaos cannon","magma lash","ethereal rapier","volcano bow","mindflayer's scepter","plasma edge","arcane sniper","frostbite fang","singularity blaster","serpent's wrath staff","polar spear thrower","heaven's bane saber","temporal bow","abyssal cleaver scythe","supernova blaster","astral scepter","voidwalker rifle","soul reaper's scythe","shockwave hammer","infernal gauntlets","holy avenger sword","void walker's staff","venomous fang thrower","stellar bow","flamestrike lance","spectral dagger","divine crossbow","ethereal slicer","chaos orb wand","shadowstorm shuriken","lunar blaster cannon","time-bender's scythe","voidfire rapier","voltaic bow","mindflayer's mind staff","plasma storm blade","arcane storm sniper","frostbite gauntlets","quasar cannon","necrotic serpent staff","void rift spear thrower","heaven's wrath saber","celestial time bow","voidcleaver's scythe","novaflare blaster","ethereal astral wand","dark matter annihilator"]
skills= ["fireball","flaming arrow","meteor shot","hardening lava","firestorm","wall of flames","volcanic eruption","thunder bolt","ball of lightning","thunder cage","volt dash","thunderclap","lightning nova","frostbolt","glacial shard","ice blast","frostbite","iceberg","blizzard","lava burst","inferno arrow","molten strike","molten trap","scorching whirlwind","flame shield","volcanic fury","static shock","electrified arrow","electro trap","charged dash","thunder surge","storm nova","frost nova","icy needle","arctic blast","frozen trap","glacier wall","polar vortex","solar flare","lunar arrow","celestial beam","starfall","cosmic explosion","astral shield","supernova","poison dart","toxic cloud","venomous trap","venom dash","noxious wave","plague storm","earthquake","rock barrage","stone spike","earthen trap","mountain fortress","tectonic upheaval","shadow strike","nightfall arrow","moonlit blade","shadow trap","abyssal wave","umbral shield","eclipse burst","sonic blast","shockwave arrow","thunderstrike","wind dash","cyclone step","tempest surge","acidic spit","corrosive arrow","venomous burst","toxic shock","slimy fortress","noxious apocalypse","solar eruption","lunar beam","celestial arrow","starlight trap","cosmic barrage","astral barrier","galactic storm","venomous strike","acid rain","corrosion field","toxic leap","poisonous whirl","plague burst","quake shock","stone wave","tectonic trap","earthslide","mountain rush","cataclysmic upheaval","shadow burst","nightshade arrow","moonshadow strike","shadow veil","darkness infusion","umbral fortress","eclipsed doom","sonic boom","thunderstrike arrow","stormy trap","wind whirl","typhoon step","tempest tornado","acidic explosion","corrosive cloud","venomous storm","toxic vortex","slime tsunami","noxious obliteration"]
consumable= ["health potion","stamina potion","endurance potion","bread","water","tea","invisibility potion","speed potion","adrenaline","stealth potion","farmer's meal","honey-glazed ham","forstberry tart","apple pie","steak","elixir of vitality","mana potion","strength potion","energy bar","fruit smoothie","fire resistance potion","wisdom elixir","chocolate cake","revitalizing tea","invisibility cloak","agility potion","mind-boosting potion","grilled fish","thunderberry pie","mango sorbet","teleportation potion","ironskin elixir","luck potion","spicy curry","moonlight dew","stealthy shroom soup","honeyed nectar","dragon's breath potion","sparkling cider","bison steak","ether infusion","berry explosion elixir","phoenix feather potion","golden truffle risotto","sparkling water","wisdom potion","energy drink","iron brew","sweet pastry","fireball elixir","cinnamon roll","shadow essence","dreamer's tea","earthroot soup","mind elixir","holy water","venomous brew","frostbite potion","blueberry muffin","celestial nectar","dexterity potion","cheese platter","nightshade elixir","melon sorbet","angel's grace potion","thunderstorm brew","sunflower tea","venus flytrap salad","mystic infusion","ghost pepper potion","golden honeycomb","dragonfruit elixir","shadowmeld tea","moonlight potion","quicksilver elixir","lunar nectar","amber ale","soulstone soup","volcano chili","starlight essence","mystic muffin","echoing elixir","serpent scale potion","essence of time","blizzard brew","sunfire elixir","celestial tea","void essence","ruby red potion","eternal soup","twilight infusion","stellar sorbet","frostbite tea","crimson elixir","enigmatic brew","oracle's gaze potion","dragon's blood elixir","mystical pastry","banshee's wail soup","heavenly honey","ancient elixir","voidfire potion","arcane apple pie","shadowsilk tea","luminous nectar","fury infusion","phantom pepper elixir","crystalized tea","whispers in the wind potion","astral ambrosia","radiant elixir","obsidian brew","ethereal soup","cosmic cake","hallowed honey","shadowstrike tea","timeless elixir","voidwalker potion","celestial cheesecake"]

armor_helmets= ["The honored one's blindfold","assassin's hood","odin's crown","knight's helmet","mage's hat","ranger's hood","warrior's helm","sorcerer's hat","paladin's helm","rogue's mask","berserker's mask","elementalist's crown","duelist's hat","necromancer's hood","beastmaster's helm","wanderer's hat","inquisitor's hood","archer's hat","alchemist's hood","druid's crown","sellsword's helm","monk's hood","knight-commander's helmet","elemental sorcerer's hat","divine paladin's helm","shadow assassin's mask","mystic seer's hood","ancient guardian's helm", "null"]
armor_helmets_values= [40,25,50,30,20,22,35,25,40,28,30,25,28,26,32,24,38,30,32,28,34,26,45,35,50,40,40,55, 0]

armor_body= ["The honored one's jacket","assassin's robe","thor's chainmail","knight's plate armor","mage's robe","ranger's cloak","warrior's chestplate","sorcerer's robe","paladin's chestplate","rogue's leather vest","berserker's chestguard","elementalist's robe","duelist's attire","necromancer's cloak","beastmaster's chestplate","wanderer's coat","inquisitor's vestment","archer's tunic","alchemist's robe","druid's robe","sellsword's chestguard","monk's robe","knight-commander's plate","elemental sorcerer's robe","divine paladin's chestplate","shadow assassin's cloak","mystic seer's robe","ancient guardian's armor", "null"]
armor_body_values= [35,30,70,40,25,28,45,30,50,35,38,32,36,34,42,30,48,38,42,36,44,32,55,40,60,45,50,65, 0]

armor_arms= ["assassin's gloves","tyr's gauntlets","knight's gauntlets","mage's gloves","ranger's gloves","warrior's bracers","sorcerer's gloves","paladin's gauntlets","rogue's fingerless gloves","berserker's wristguards","elementalist's cuffs","duelist's gloves","necromancer's gloves","beastmaster's gauntlets","wanderer's gloves","inquisitor's cuffs","archer's gloves","alchemist's gloves","druid's bracers","sellsword's gauntlets","monk's gloves","knight-commander's gauntlets","elemental sorcerer's gloves","divine paladin's gauntlets","shadow assassin's gloves","mystic seer's gloves","ancient guardian's gauntlets", "null"]
armor_arms_values= [10,55,15,8,12,20,12,18,14,16,14,16,15,18,14,22,18,20,16,20,18,25,18,30,20,25,35, 0]

armor_legs= ["The honored one's pants","assassin's leggings","yggdrasil's leggings","knight's greaves","mage's leggings","ranger's pants","warrior's legplates","sorcerer's pants","paladin's greaves","rogue's trousers","berserker's legguards","elementalist's leggings","duelist's trousers","necromancer's pants","beastmaster's leggings","wanderer's pants","inquisitor's leggings","archer's pants","alchemist's leggings","druid's leggings","sellsword's legguards","monk's pants","knight-commander's greaves","elemental sorcerer's pants","divine paladin's greaves","shadow assassin's pants","mystic seer's pants","ancient guardian's greaves", "null"]
armor_legs_values= [25,15,43,20,12,18,25,15,30,20,22,20,24,22,26,21,28,26,30,24,32,28,35,25,40,30,35,45, 0]

armor_feet= ["The honored one's boots","assassin's boots","frigg's greaves","knight's boots","mage's shoes","ranger's boots","warrior's boots","sorcerer's shoes","paladin's boots","rogue's ankle boots","berserker's boots","elementalist's sandals","duelist's shoes","necromancer's boots","beastmaster's boots","wanderer's boots","inquisitor's boots","archer's boots","alchemist's shoes","druid's sandals","sellsword's boots","monk's sandals","knight-commander's boots","elemental sorcerer's shoes","divine paladin's boots","shadow assassin's boots","mystic seer's shoes","ancient guardian's boots", "null"]
armor_feet_values= [15,7,20,12,6,10,15,8,20,12,18,15,16,14,17,13,20,16,18,14,22,20,25,15,30,20,25,35, 0]

all_items= ["tiger's eye", "fox tail", "writer's notebook", "camera", "bottle of wine", "baseball cap", "rusty spoon", "broken compass", "rubber chicken", "singing seashell", "hand mirror", "puzzle piece", "invisible ink pen", "metal slinky", "balloon animal", "half eaten apple", "science fair award", "amethyst", "rainbow gemstone", " rubiks cube", "mystic orb", "enchanted amulet", "shadow cloak", "celestial feather", "crystalized essence", "arcane rune", "elemental shard", "ethereal mirror", "astral lantern", "luminous pebble", "dreamweaver's quill", "timeless hourglass", "starlight veil", "whispering totem", "emberstone charm", "lunar crest", "frostbound blossom", "gilded compass", "soulstone trinket", "thunderstruck relic", "aetheric beacon", "eclipsed crystal", "phoenix feather", "zephyr gem", "cursed doll", "shrouded talisman", "nebula medallion", "enigmatic scroll", "radiant prism", "ensnaring vine", "mirage pearl", "songbird's feather", "mirror of illusion", "verdant blossom", "rune of resilience", "harmony crystal", "whisperwind elixir", "silver locket", "serenity stone", "penumbral pendant", "dreamcatcher amulet", "ruby heartstone", "lava bloom seed", "crystalline vessel", "galeforce whistle", "shimmering scepter", "frostfire lantern", "arcane codex", "ephemeral feather", "tidecaller's shell", "pyroclasmic ember", "stormbringer's sigil", "illusory lantern", "crystalized tears", "enigmatic crest", "sacred sigil", "soothing breeze amulet", "lively coral", "ethereal blossom", "solar flare seed", "resonating crystal", "cursed mirror", "stargazer's lens", "volcanic emberstone", "frostfallen relic", "tranquil lotus", "vortex core", "celestial ocarina", "shadow silk scarf", "stormwhisper feather", "ember veil", "astral serpent scale", "lunar lace", "crimson phoenix plume", "sylphic whisper", "crystalized aurora", "verdant dreamcatcher", "prismatic crystal", "labyrinthine key", "starforged ingot", "harmonic conch shell", "enchanted vellum", "mysterious music box", "dreamer's journal", "emberroot sapling", "moonlit essence", "cavernous gemstone", "celestial lantern", "mirage cloak", "frostblossom seed", "echoing chime", "aetherial lens", "radiant feather", "obsidian rune stone", "serene lotus petal", "astral ribbon", "ethereal prism", "lunar blossom", "enigmatic figurine", "timeless relic"]

location= ["elven village","igloosia","miner's retreat","ancient throne room","blossom valley","oasis outpost","feywood forest","ember summit","cursed cathedral","glacial sanctuary","tempest summit","crystal spire","divine citadel","stormwatch tower","boggy haven","haunted thicket","subterranean citadel","amethyst atoll","time-worn sanctuary","celestial junction","desolate plaza","lunar sanctuary","stardust grove","aurora summit","abyssal palace","oasis of mirages","ancient tree grove","inferno citadel","oasis of echoes","haunted harbor","mystic glade","frozen fortress","volted citadel","amethyst haven"]

usernames= input("Add usernames (comma seperated and no spaces between commas): ").split(",")

for i in range(len(usernames)):
    random_helm= random.choice(armor_helmets)
    random_body= random.choice(armor_body)
    random_arms= random.choice(armor_arms)
    random_legs= random.choice(armor_legs)
    random_feet= random.choice(armor_feet)
    armor= armor_helmets_values[armor_helmets.index(random_helm)] + armor_body_values[armor_body.index(random_body)] + armor_arms_values[armor_arms.index(random_arms)] + armor_legs_values[armor_legs.index(random_legs)] + armor_feet_values[armor_feet.index(random_feet)]
    backpack= random.choices(all_items, k=random.randrange(0, 50))

    file.write(f'{"{"}\n\tusername: "{usernames[i]}",\n\tinventory: {"{"}\n\t\tequipped: {"{"}\n\t\t\tweapon: "{random.choice(weapons)}",\n\t\t\tskill: "{random.choice(skills)}",\n\t\t\tconsumable: "{random.choice(consumable)}",\n\t\t\thead: "{random_helm}",\n\t\t\ttorso: "{random_body}",\n\t\t\tarms: "{random_arms}",\n\t\t\tlegs: "{random_legs}",\n\t\t\tfeet: "{random_feet}"\n\t\t{"}"},\n\t\tbackpack: [\n\t\t\t{backpack}\n\t\t]\n\t{"}"},\n\thealth: {random.randint(50, 250)},\n\tstamina: {random.randint(50, 250)},\n\tarmor: {armor},\n\tmastery: {"{"}\n\t\tweapon: {random.randint(0, 30)},\n\t\tskill: {random.randint(0, 30)}\n\t{"}"},\n\tsavepoint: {"{"}\n\t\tlocation: "{random.choice(location)}",\n\t\tdate: Date()\n\t{"}"}\n{"}"},\n')


file.close()
print("\n#########All outputs have been added to the t_InsertOutput.txt file#########\n")